name: zeal4_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project with Serverpod.
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  crypto: ^3.0.5
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  gap: ^3.0.1
  get: 4.6.6
  intl: ^0.19.0
  serverpod_flutter: 2.1.2
  syncfusion_flutter_charts: ^26.2.14
  zeal4_client:
    path: ../zeal4_client

dev_dependencies:
  flutter_lints: ">=3.0.0 <5.0.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
