version: "3.7"

services:
  postgres:
    image: postgres:16.3
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: zeal4
      POSTGRES_PASSWORD: "gAlO2PStdaRJo_tgZhVrMFmf9bOTdLcx"
    volumes:
      - zeal4_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "yW-oGWTa_uXWNG5sCUUGl6R-n_4Uep-A"
    environment:
      - REDIS_REPLICATION_MODE=master

  adminer:
    image: adminer
    depends_on:
      - "postgres"
    ports:
      - 8092:8080

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9901:9901"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "v4f2EpmS7HLBsL_vIybQlBiaFeZW5cW4"
    command: server --address "0.0.0.0:9900" --console-address ":9901" /data

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:ro
      - ./mosquitto/log/:/mosquitto/log/
      - ./mosquitto/data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  zeal4_data:
  minio_data:
