name: zeal4_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  mailer: ^6.6.0
  serverpod: 3.0.0
  serverpod_auth_server: 3.0.0
  serverpod_cloud_storage_gcp: 3.0.0
  serverpod_cloud_storage_s3: 3.0.0

dev_dependencies:
  lints: ^6.0.0
